# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      JAVA_OPTS: "-Xmx512m -XX:MaxMetaspaceSize=256m"
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'

    # NB: It's possible to create a smarter "layered" cache that
    # caches jar dependencies separately from the build cache.
    # Out-of-scoping until it becomes an issue
    - name: Store/restore gradle cache
      uses: actions/cache@v2
      with:
        path: |
          .gradle
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: "gradle-v1-${{github.run_id}}"
        restore-keys: |
          gradle-v1
          gradle

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build with Gradle
      run: ./gradlew jib --build-cache
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
